name: Build Kivy APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev automake

      - name: Install Python dependencies
        run: |
          python -m pip install --user --upgrade cython virtualenv buildozer==1.5.0 python-for-android

      - name: Install Android SDK
        run: |
          # Install Android SDK command-line tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O /tmp/cmdline-tools.zip
          unzip -q /tmp/cmdline-tools.zip -d /tmp
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          mv /tmp/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/
          export ANDROID_HOME=$HOME/android-sdk
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          # Accept all licenses
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Build the APK
        run: |
          # Ensure buildozer is in PATH
          export PATH=$HOME/.local/bin:$PATH
          # Build the APK
          buildozer -