name: Build Tarot APK

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev automake libjpeg-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install cython==0.29.33 buildozer==1.5.0

      - name: Setup Android SDK and NDK
        run: |
          mkdir -p $HOME/android-sdk
          export ANDROID_HOME=$HOME/android-sdk
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV

          # Download command line tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O /tmp/cmdline-tools.zip
          unzip -q /tmp/cmdline-tools.zip -d /tmp
          mkdir -p $ANDROID_HOME/cmdline-tools/latest
          mv /tmp/cmdline-tools/* $ANDROID_HOME/cmdline-tools/latest/

          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH

          yes | sdkmanager --licenses

          # Install components (use 33.0.2 to match aidl requirement)
          yes | sdkmanager "build-tools;33.0.2" "platforms;android-33" "platform-tools" "tools"

          # Download NDK 25b
          wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip -O /tmp/ndk.zip
          unzip -q /tmp/ndk.zip -d $ANDROID_HOME
          mkdir -p $ANDROID_HOME/ndk
          mv $ANDROID_HOME/android-ndk-r25b $ANDROID_HOME/ndk/25b

      - name: Build the APK
        run: |
          export PATH=$HOME/.local/bin:$PATH
          unset ANDROID_NDK ANDROID_NDK_ROOT ANDROID_NDK_LATEST_HOME ANDROID_NDK_HOME
          export ANDROID_HOME=$HOME/android-sdk
          export ANDROID_SDK_ROOT=$HOME/android-sdk

          buildozer android clean || true
          buildozer -v android debug

      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: tarot-apk
          path: bin/*.apk
