name: Build Kivy APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Buildozer dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev automake
          pip install --user --upgrade cython virtualenv
          pip install --user --upgrade buildozer
          echo 'export PATH=$PATH:~/.local/bin/' >> $GITHUB_ENV

      - name: Set up Java
        run: |
          sudo apt install -y openjdk-17-jdk
          echo 'JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64' >> $GITHUB_ENV
          sudo update-java-alternatives --set java-1.17.0-openjdk-amd64
          echo '/usr/lib/jvm/java-17-openjdk-amd64/bin' >> $GITHUB_ENV

      - name: Clean previous build
        run: buildozer android clean
      
      - name: Build the APK
        run: buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: tarot-app-apk
          path: bin/tarot-app-*.apk
